//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace HtsLoom
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class ActivityCenter
    {
    
        private int _threshold;
    
        private System.Collections.Generic.List<System.Collections.Generic.List<Point>> _regions;
    
        private CameraName _camera;
    
        public ActivityCenter()
        {
            _threshold = 100;
            _regions = new System.Collections.Generic.List<System.Collections.Generic.List<Point>>();
        }
    
        protected ActivityCenter(ActivityCenter other)
        {
            _threshold = other._threshold;
            _regions = other._regions;
            _camera = other._camera;
        }
    
        /// <summary>
        /// Threshold for the blob tracking.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("threshold")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="threshold")]
        [System.ComponentModel.DescriptionAttribute("Threshold for the blob tracking.")]
        public int Threshold
        {
            get
            {
                return _threshold;
            }
            set
            {
                _threshold = value;
            }
        }
    
        /// <summary>
        /// Region for the tracking.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("regions", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="regions")]
        [System.ComponentModel.DescriptionAttribute("Region for the tracking.")]
        public System.Collections.Generic.List<System.Collections.Generic.List<Point>> Regions
        {
            get
            {
                return _regions;
            }
            set
            {
                _regions = value;
            }
        }
    
        /// <summary>
        /// Activity center camera
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("camera", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="camera")]
        [System.ComponentModel.DescriptionAttribute("Activity center camera")]
        public CameraName Camera
        {
            get
            {
                return _camera;
            }
            set
            {
                _camera = value;
            }
        }
    
        public System.IObservable<ActivityCenter> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new ActivityCenter(this)));
        }
    
        public System.IObservable<ActivityCenter> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new ActivityCenter(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Threshold = " + _threshold + ", ");
            stringBuilder.Append("Regions = " + _regions + ", ");
            stringBuilder.Append("Camera = " + _camera);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class ActivityTracking
    {
    
        private int _threshold;
    
        private System.Collections.Generic.List<System.Collections.Generic.List<Point>> _regions;
    
        public ActivityTracking()
        {
            _threshold = 100;
            _regions = new System.Collections.Generic.List<System.Collections.Generic.List<Point>>();
        }
    
        protected ActivityTracking(ActivityTracking other)
        {
            _threshold = other._threshold;
            _regions = other._regions;
        }
    
        /// <summary>
        /// Threshold for the blob tracking.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("threshold")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="threshold")]
        [System.ComponentModel.DescriptionAttribute("Threshold for the blob tracking.")]
        public int Threshold
        {
            get
            {
                return _threshold;
            }
            set
            {
                _threshold = value;
            }
        }
    
        /// <summary>
        /// Region for the tracking.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("regions", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="regions")]
        [System.ComponentModel.DescriptionAttribute("Region for the tracking.")]
        public System.Collections.Generic.List<System.Collections.Generic.List<Point>> Regions
        {
            get
            {
                return _regions;
            }
            set
            {
                _regions = value;
            }
        }
    
        public System.IObservable<ActivityTracking> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new ActivityTracking(this)));
        }
    
        public System.IObservable<ActivityTracking> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new ActivityTracking(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Threshold = " + _threshold + ", ");
            stringBuilder.Append("Regions = " + _regions);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Camera
    {
    
        private string _serialNumber;
    
        private double _exposureTime;
    
        private double _gain;
    
        private int _binning;
    
        private TriggerName _trigger;
    
        private Tracking _cameraTracking;
    
        public Camera()
        {
            _exposureTime = 1000D;
            _gain = 0D;
            _binning = 1;
            _trigger = TriggerName.Trigger0;
        }
    
        protected Camera(Camera other)
        {
            _serialNumber = other._serialNumber;
            _exposureTime = other._exposureTime;
            _gain = other._gain;
            _binning = other._binning;
            _trigger = other._trigger;
            _cameraTracking = other._cameraTracking;
        }
    
        /// <summary>
        /// The serial number of the camera.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("serialNumber", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="serialNumber")]
        [System.ComponentModel.DescriptionAttribute("The serial number of the camera.")]
        public string SerialNumber
        {
            get
            {
                return _serialNumber;
            }
            set
            {
                _serialNumber = value;
            }
        }
    
        /// <summary>
        /// The exposure time of the sensor, in microseconds.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("exposureTime")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="exposureTime")]
        [System.ComponentModel.DescriptionAttribute("The exposure time of the sensor, in microseconds.")]
        public double ExposureTime
        {
            get
            {
                return _exposureTime;
            }
            set
            {
                _exposureTime = value;
            }
        }
    
        /// <summary>
        /// The camera gain.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("gain")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="gain")]
        [System.ComponentModel.DescriptionAttribute("The camera gain.")]
        public double Gain
        {
            get
            {
                return _gain;
            }
            set
            {
                _gain = value;
            }
        }
    
        /// <summary>
        /// The camera binning configuration.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("binning")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="binning")]
        [System.ComponentModel.DescriptionAttribute("The camera binning configuration.")]
        public int Binning
        {
            get
            {
                return _binning;
            }
            set
            {
                _binning = value;
            }
        }
    
        /// <summary>
        /// The name of the trigger.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("trigger")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="trigger")]
        [System.ComponentModel.DescriptionAttribute("The name of the trigger.")]
        public TriggerName Trigger
        {
            get
            {
                return _trigger;
            }
            set
            {
                _trigger = value;
            }
        }
    
        /// <summary>
        /// Tracking Parameters.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("cameraTracking")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="cameraTracking")]
        [System.ComponentModel.DescriptionAttribute("Tracking Parameters.")]
        public Tracking CameraTracking
        {
            get
            {
                return _cameraTracking;
            }
            set
            {
                _cameraTracking = value;
            }
        }
    
        public System.IObservable<Camera> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Camera(this)));
        }
    
        public System.IObservable<Camera> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Camera(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("SerialNumber = " + _serialNumber + ", ");
            stringBuilder.Append("ExposureTime = " + _exposureTime + ", ");
            stringBuilder.Append("Gain = " + _gain + ", ");
            stringBuilder.Append("Binning = " + _binning + ", ");
            stringBuilder.Append("Trigger = " + _trigger + ", ");
            stringBuilder.Append("CameraTracking = " + _cameraTracking);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class CameraController
    {
    
        private string _portName;
    
        private System.Collections.Generic.Dictionary<TriggerName, CameraControllerTrigger> _triggers;
    
        public CameraController()
        {
            _triggers = new System.Collections.Generic.Dictionary<TriggerName, CameraControllerTrigger>();
        }
    
        protected CameraController(CameraController other)
        {
            _portName = other._portName;
            _triggers = other._triggers;
        }
    
        /// <summary>
        /// The name of the device serial port.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("portName", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="portName")]
        [System.ComponentModel.DescriptionAttribute("The name of the device serial port.")]
        public string PortName
        {
            get
            {
                return _portName;
            }
            set
            {
                _portName = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("triggers", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="triggers")]
        public System.Collections.Generic.Dictionary<TriggerName, CameraControllerTrigger> Triggers
        {
            get
            {
                return _triggers;
            }
            set
            {
                _triggers = value;
            }
        }
    
        public System.IObservable<CameraController> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new CameraController(this)));
        }
    
        public System.IObservable<CameraController> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new CameraController(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("PortName = " + _portName + ", ");
            stringBuilder.Append("Triggers = " + _triggers);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class CameraControllerTrigger
    {
    
        private int _frequency;
    
        public CameraControllerTrigger()
        {
            _frequency = 50;
        }
    
        protected CameraControllerTrigger(CameraControllerTrigger other)
        {
            _frequency = other._frequency;
        }
    
        /// <summary>
        /// The frequency of the camera TTL trigger.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("frequency")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="frequency")]
        [System.ComponentModel.DescriptionAttribute("The frequency of the camera TTL trigger.")]
        public int Frequency
        {
            get
            {
                return _frequency;
            }
            set
            {
                _frequency = value;
            }
        }
    
        public System.IObservable<CameraControllerTrigger> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new CameraControllerTrigger(this)));
        }
    
        public System.IObservable<CameraControllerTrigger> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new CameraControllerTrigger(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Frequency = " + _frequency);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum CameraName
    {
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraNorth")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraNorth")]
        CameraNorth = 0,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraSouth")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraSouth")]
        CameraSouth = 1,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraTop")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraTop")]
        CameraTop = 2,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraEast")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraEast")]
        CameraEast = 3,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraWest")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraWest")]
        CameraWest = 4,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraPatch1")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraPatch1")]
        CameraPatch1 = 5,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraPatch2")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraPatch2")]
        CameraPatch2 = 6,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraPatch3")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraPatch3")]
        CameraPatch3 = 7,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraPatch4")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraPatch4")]
        CameraPatch4 = 8,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraPatch5")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraPatch5")]
        CameraPatch5 = 9,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraPatch6")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraPatch6")]
        CameraPatch6 = 10,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraLightMonitor")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraLightMonitor")]
        CameraLightMonitor = 11,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="CameraNest")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="CameraNest")]
        CameraNest = 12,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Experiment
    {
    
        private string _workflow;
    
        private string _commit;
    
        private string _repositoryUrl;
    
        private Rig _rig;
    
        public Experiment()
        {
            _rig = new Rig();
        }
    
        protected Experiment(Experiment other)
        {
            _workflow = other._workflow;
            _commit = other._commit;
            _repositoryUrl = other._repositoryUrl;
            _rig = other._rig;
        }
    
        /// <summary>
        /// Path to the workflow running the experiment.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("workflow", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="workflow")]
        [System.ComponentModel.DescriptionAttribute("Path to the workflow running the experiment.")]
        public string Workflow
        {
            get
            {
                return _workflow;
            }
            set
            {
                _workflow = value;
            }
        }
    
        /// <summary>
        /// Commit hash of the experiment repo.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("commit", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="commit")]
        [System.ComponentModel.DescriptionAttribute("Commit hash of the experiment repo.")]
        public string Commit
        {
            get
            {
                return _commit;
            }
            set
            {
                _commit = value;
            }
        }
    
        /// <summary>
        /// The URL of the git repository used to version experiment source code.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("repositoryUrl", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="repositoryUrl")]
        [System.ComponentModel.DescriptionAttribute("The URL of the git repository used to version experiment source code.")]
        public string RepositoryUrl
        {
            get
            {
                return _repositoryUrl;
            }
            set
            {
                _repositoryUrl = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("rig", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="rig")]
        public Rig Rig
        {
            get
            {
                return _rig;
            }
            set
            {
                _rig = value;
            }
        }
    
        public System.IObservable<Experiment> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Experiment(this)));
        }
    
        public System.IObservable<Experiment> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Experiment(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Workflow = " + _workflow + ", ");
            stringBuilder.Append("Commit = " + _commit + ", ");
            stringBuilder.Append("RepositoryUrl = " + _repositoryUrl + ", ");
            stringBuilder.Append("Rig = " + _rig);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum FeederName
    {
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Feeder1")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Feeder1")]
        Feeder1 = 0,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Feeder2")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Feeder2")]
        Feeder2 = 1,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Feeder3")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Feeder3")]
        Feeder3 = 2,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Feeder4")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Feeder4")]
        Feeder4 = 3,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Feeder5")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Feeder5")]
        Feeder5 = 4,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Feeder6")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Feeder6")]
        Feeder6 = 5,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class HarpTimestampGeneratorGen3
    {
    
        private string _portName;
    
        public HarpTimestampGeneratorGen3()
        {
        }
    
        protected HarpTimestampGeneratorGen3(HarpTimestampGeneratorGen3 other)
        {
            _portName = other._portName;
        }
    
        /// <summary>
        /// The name of the device serial port.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("portName", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="portName")]
        [System.ComponentModel.DescriptionAttribute("The name of the device serial port.")]
        public string PortName
        {
            get
            {
                return _portName;
            }
            set
            {
                _portName = value;
            }
        }
    
        public System.IObservable<HarpTimestampGeneratorGen3> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new HarpTimestampGeneratorGen3(this)));
        }
    
        public System.IObservable<HarpTimestampGeneratorGen3> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new HarpTimestampGeneratorGen3(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("PortName = " + _portName);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class LightCycle
    {
    
        private string _commandSocket;
    
        private string _eventSocket;
    
        private string _roomName;
    
        private string _configFileName;
    
        public LightCycle()
        {
            _commandSocket = ">tcp://localhost:4304";
            _eventSocket = ">tcp://localhost:4303";
            _roomName = "Aeon3";
            _configFileName = "lightcycle.config";
        }
    
        protected LightCycle(LightCycle other)
        {
            _commandSocket = other._commandSocket;
            _eventSocket = other._eventSocket;
            _roomName = other._roomName;
            _configFileName = other._configFileName;
        }
    
        /// <summary>
        /// Specifies the endpoint to send commands to the Light Server.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("commandSocket")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="commandSocket")]
        [System.ComponentModel.DescriptionAttribute("Specifies the endpoint to send commands to the Light Server.")]
        public string CommandSocket
        {
            get
            {
                return _commandSocket;
            }
            set
            {
                _commandSocket = value;
            }
        }
    
        /// <summary>
        /// Specifies the endpoint to send commands to the Light Server.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("eventSocket")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="eventSocket")]
        [System.ComponentModel.DescriptionAttribute("Specifies the endpoint to send commands to the Light Server.")]
        public string EventSocket
        {
            get
            {
                return _eventSocket;
            }
            set
            {
                _eventSocket = value;
            }
        }
    
        /// <summary>
        /// The name of the room to monitor and control.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("roomName")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="roomName")]
        [System.ComponentModel.DescriptionAttribute("The name of the room to monitor and control.")]
        public string RoomName
        {
            get
            {
                return _roomName;
            }
            set
            {
                _roomName = value;
            }
        }
    
        /// <summary>
        /// The name of the CSV file describing the light model, where each row represents one whole minute and the red, cold white and warm white, light levels set for that minute.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("configFileName")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="configFileName")]
        [System.ComponentModel.DescriptionAttribute("The name of the CSV file describing the light model, where each row represents on" +
            "e whole minute and the red, cold white and warm white, light levels set for that" +
            " minute.")]
        public string ConfigFileName
        {
            get
            {
                return _configFileName;
            }
            set
            {
                _configFileName = value;
            }
        }
    
        public System.IObservable<LightCycle> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new LightCycle(this)));
        }
    
        public System.IObservable<LightCycle> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new LightCycle(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("CommandSocket = " + _commandSocket + ", ");
            stringBuilder.Append("EventSocket = " + _eventSocket + ", ");
            stringBuilder.Append("RoomName = " + _roomName + ", ");
            stringBuilder.Append("ConfigFileName = " + _configFileName);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Point
    {
    
        private int _x;
    
        private int _y;
    
        public Point()
        {
            _x = 0;
            _y = 0;
        }
    
        protected Point(Point other)
        {
            _x = other._x;
            _y = other._y;
        }
    
        /// <summary>
        /// The X coordinate of the point
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("x")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="x")]
        [System.ComponentModel.DescriptionAttribute("The X coordinate of the point")]
        public int X
        {
            get
            {
                return _x;
            }
            set
            {
                _x = value;
            }
        }
    
        /// <summary>
        /// The Y coordinate of the point
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("y")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="y")]
        [System.ComponentModel.DescriptionAttribute("The Y coordinate of the point")]
        public int Y
        {
            get
            {
                return _y;
            }
            set
            {
                _y = value;
            }
        }
    
        public System.IObservable<Point> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Point(this)));
        }
    
        public System.IObservable<Point> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Point(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("X = " + _x + ", ");
            stringBuilder.Append("Y = " + _y);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Rig
    {
    
        private HarpTimestampGeneratorGen3 _clockSynchronizer;
    
        private CameraController _cameraSynchronizer;
    
        private System.Collections.Generic.Dictionary<CameraName, Camera> _cameras;
    
        private System.Collections.Generic.Dictionary<FeederName, UndergroundFeeder> _feeders;
    
        private System.Collections.Generic.Dictionary<string, WeightScale> _nest;
    
        private ActivityCenter _activityCenter;
    
        private LightCycle _lightCycle;
    
        public Rig()
        {
            _clockSynchronizer = new HarpTimestampGeneratorGen3();
            _cameraSynchronizer = new CameraController();
            _cameras = new System.Collections.Generic.Dictionary<CameraName, Camera>();
            _feeders = new System.Collections.Generic.Dictionary<FeederName, UndergroundFeeder>();
            _nest = new System.Collections.Generic.Dictionary<string, WeightScale>();
            _activityCenter = new ActivityCenter();
            _lightCycle = new LightCycle();
        }
    
        protected Rig(Rig other)
        {
            _clockSynchronizer = other._clockSynchronizer;
            _cameraSynchronizer = other._cameraSynchronizer;
            _cameras = other._cameras;
            _feeders = other._feeders;
            _nest = other._nest;
            _activityCenter = other._activityCenter;
            _lightCycle = other._lightCycle;
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("clockSynchronizer", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="clockSynchronizer")]
        public HarpTimestampGeneratorGen3 ClockSynchronizer
        {
            get
            {
                return _clockSynchronizer;
            }
            set
            {
                _clockSynchronizer = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("cameraSynchronizer", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="cameraSynchronizer")]
        public CameraController CameraSynchronizer
        {
            get
            {
                return _cameraSynchronizer;
            }
            set
            {
                _cameraSynchronizer = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("cameras", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="cameras")]
        public System.Collections.Generic.Dictionary<CameraName, Camera> Cameras
        {
            get
            {
                return _cameras;
            }
            set
            {
                _cameras = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("feeders", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="feeders")]
        public System.Collections.Generic.Dictionary<FeederName, UndergroundFeeder> Feeders
        {
            get
            {
                return _feeders;
            }
            set
            {
                _feeders = value;
            }
        }
    
        /// <summary>
        /// Weight scale parameters.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("nest", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="nest")]
        [System.ComponentModel.DescriptionAttribute("Weight scale parameters.")]
        public System.Collections.Generic.Dictionary<string, WeightScale> Nest
        {
            get
            {
                return _nest;
            }
            set
            {
                _nest = value;
            }
        }
    
        /// <summary>
        /// Activity in the center of the arena.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("activityCenter", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="activityCenter")]
        [System.ComponentModel.DescriptionAttribute("Activity in the center of the arena.")]
        public ActivityCenter ActivityCenter
        {
            get
            {
                return _activityCenter;
            }
            set
            {
                _activityCenter = value;
            }
        }
    
        /// <summary>
        /// LightCycle components for the arena.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("lightCycle", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="lightCycle")]
        [System.ComponentModel.DescriptionAttribute("LightCycle components for the arena.")]
        public LightCycle LightCycle
        {
            get
            {
                return _lightCycle;
            }
            set
            {
                _lightCycle = value;
            }
        }
    
        public System.IObservable<Rig> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Rig(this)));
        }
    
        public System.IObservable<Rig> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Rig(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("ClockSynchronizer = " + _clockSynchronizer + ", ");
            stringBuilder.Append("CameraSynchronizer = " + _cameraSynchronizer + ", ");
            stringBuilder.Append("Cameras = " + _cameras + ", ");
            stringBuilder.Append("Feeders = " + _feeders + ", ");
            stringBuilder.Append("Nest = " + _nest + ", ");
            stringBuilder.Append("ActivityCenter = " + _activityCenter + ", ");
            stringBuilder.Append("LightCycle = " + _lightCycle);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class Tracking
    {
    
        private System.Collections.Generic.Dictionary<string, ActivityTracking> _blobTracking;
    
        public Tracking()
        {
            _blobTracking = new System.Collections.Generic.Dictionary<string, ActivityTracking>();
        }
    
        protected Tracking(Tracking other)
        {
            _blobTracking = other._blobTracking;
        }
    
        /// <summary>
        /// The subject tracking in the arena.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("blobTracking", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="blobTracking")]
        [System.ComponentModel.DescriptionAttribute("The subject tracking in the arena.")]
        public System.Collections.Generic.Dictionary<string, ActivityTracking> BlobTracking
        {
            get
            {
                return _blobTracking;
            }
            set
            {
                _blobTracking = value;
            }
        }
    
        public System.IObservable<Tracking> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Tracking(this)));
        }
    
        public System.IObservable<Tracking> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Tracking(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("BlobTracking = " + _blobTracking);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum TriggerName
    {
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Trigger0")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Trigger0")]
        Trigger0 = 0,
    
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Trigger1")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Trigger1")]
        Trigger1 = 1,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class UndergroundFeeder
    {
    
        private string _portName;
    
        private int _pelletDeliveryRetryCount;
    
        private double _pelletDeliveryTimeout;
    
        private double _wheelRadius;
    
        public UndergroundFeeder()
        {
            _pelletDeliveryRetryCount = 2;
            _pelletDeliveryTimeout = 1D;
            _wheelRadius = -4D;
        }
    
        protected UndergroundFeeder(UndergroundFeeder other)
        {
            _portName = other._portName;
            _pelletDeliveryRetryCount = other._pelletDeliveryRetryCount;
            _pelletDeliveryTimeout = other._pelletDeliveryTimeout;
            _wheelRadius = other._wheelRadius;
        }
    
        /// <summary>
        /// The name of the device serial port.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("portName", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="portName")]
        [System.ComponentModel.DescriptionAttribute("The name of the device serial port.")]
        public string PortName
        {
            get
            {
                return _portName;
            }
            set
            {
                _portName = value;
            }
        }
    
        /// <summary>
        /// The number of times to retry a failed pellet delivery.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("pelletDeliveryRetryCount")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="pelletDeliveryRetryCount")]
        [System.ComponentModel.DescriptionAttribute("The number of times to retry a failed pellet delivery.")]
        public int PelletDeliveryRetryCount
        {
            get
            {
                return _pelletDeliveryRetryCount;
            }
            set
            {
                _pelletDeliveryRetryCount = value;
            }
        }
    
        /// <summary>
        /// The amount of time to wait for pellet detection before reporting a failure.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("pelletDeliveryTimeout")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="pelletDeliveryTimeout")]
        [System.ComponentModel.DescriptionAttribute("The amount of time to wait for pellet detection before reporting a failure.")]
        public double PelletDeliveryTimeout
        {
            get
            {
                return _pelletDeliveryTimeout;
            }
            set
            {
                _pelletDeliveryTimeout = value;
            }
        }
    
        /// <summary>
        /// The radius of the wheel, in centimeters.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("wheelRadius")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="wheelRadius")]
        [System.ComponentModel.DescriptionAttribute("The radius of the wheel, in centimeters.")]
        public double WheelRadius
        {
            get
            {
                return _wheelRadius;
            }
            set
            {
                _wheelRadius = value;
            }
        }
    
        public System.IObservable<UndergroundFeeder> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new UndergroundFeeder(this)));
        }
    
        public System.IObservable<UndergroundFeeder> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new UndergroundFeeder(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("PortName = " + _portName + ", ");
            stringBuilder.Append("PelletDeliveryRetryCount = " + _pelletDeliveryRetryCount + ", ");
            stringBuilder.Append("PelletDeliveryTimeout = " + _pelletDeliveryTimeout + ", ");
            stringBuilder.Append("WheelRadius = " + _wheelRadius);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class WeightScale
    {
    
        private string _portName;
    
        private int _filterWindow;
    
        private double _weightBaselineRefactoryPeriod;
    
        public WeightScale()
        {
            _filterWindow = 40;
            _weightBaselineRefactoryPeriod = 5D;
        }
    
        protected WeightScale(WeightScale other)
        {
            _portName = other._portName;
            _filterWindow = other._filterWindow;
            _weightBaselineRefactoryPeriod = other._weightBaselineRefactoryPeriod;
        }
    
        /// <summary>
        /// The name of the device serial port.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("portName", Required=Newtonsoft.Json.Required.Always)]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="portName")]
        [System.ComponentModel.DescriptionAttribute("The name of the device serial port.")]
        public string PortName
        {
            get
            {
                return _portName;
            }
            set
            {
                _portName = value;
            }
        }
    
        /// <summary>
        /// Sliding window size of the weight linear regression filter.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("filterWindow")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="filterWindow")]
        [System.ComponentModel.DescriptionAttribute("Sliding window size of the weight linear regression filter.")]
        public int FilterWindow
        {
            get
            {
                return _filterWindow;
            }
            set
            {
                _filterWindow = value;
            }
        }
    
        /// <summary>
        /// The time between consecutive weight baseline when subject in center of arena in seconds.
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("weightBaselineRefactoryPeriod")]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="weightBaselineRefactoryPeriod")]
        [System.ComponentModel.DescriptionAttribute("The time between consecutive weight baseline when subject in center of arena in s" +
            "econds.")]
        public double WeightBaselineRefactoryPeriod
        {
            get
            {
                return _weightBaselineRefactoryPeriod;
            }
            set
            {
                _weightBaselineRefactoryPeriod = value;
            }
        }
    
        public System.IObservable<WeightScale> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new WeightScale(this)));
        }
    
        public System.IObservable<WeightScale> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new WeightScale(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("PortName = " + _portName + ", ");
            stringBuilder.Append("FilterWindow = " + _filterWindow + ", ");
            stringBuilder.Append("WeightBaselineRefactoryPeriod = " + _weightBaselineRefactoryPeriod);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToJson
    {
    
        public Newtonsoft.Json.Formatting Formatting { get; set; }

        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            var formatting = Formatting;
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value, formatting));
        }

        public System.IObservable<string> Process(System.IObservable<ActivityCenter> source)
        {
            return Process<ActivityCenter>(source);
        }

        public System.IObservable<string> Process(System.IObservable<ActivityTracking> source)
        {
            return Process<ActivityTracking>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Camera> source)
        {
            return Process<Camera>(source);
        }

        public System.IObservable<string> Process(System.IObservable<CameraController> source)
        {
            return Process<CameraController>(source);
        }

        public System.IObservable<string> Process(System.IObservable<CameraControllerTrigger> source)
        {
            return Process<CameraControllerTrigger>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Experiment> source)
        {
            return Process<Experiment>(source);
        }

        public System.IObservable<string> Process(System.IObservable<HarpTimestampGeneratorGen3> source)
        {
            return Process<HarpTimestampGeneratorGen3>(source);
        }

        public System.IObservable<string> Process(System.IObservable<LightCycle> source)
        {
            return Process<LightCycle>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Point> source)
        {
            return Process<Point>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Rig> source)
        {
            return Process<Rig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Tracking> source)
        {
            return Process<Tracking>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UndergroundFeeder> source)
        {
            return Process<UndergroundFeeder>(source);
        }

        public System.IObservable<string> Process(System.IObservable<WeightScale> source)
        {
            return Process<WeightScale>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ActivityCenter>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ActivityTracking>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Camera>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<CameraController>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<CameraControllerTrigger>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Experiment>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HarpTimestampGeneratorGen3>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<LightCycle>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Point>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Rig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Tracking>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UndergroundFeeder>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<WeightScale>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<ActivityCenter>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<ActivityCenter> source)
        {
            return Process<ActivityCenter>(source);
        }

        public System.IObservable<string> Process(System.IObservable<ActivityTracking> source)
        {
            return Process<ActivityTracking>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Camera> source)
        {
            return Process<Camera>(source);
        }

        public System.IObservable<string> Process(System.IObservable<CameraController> source)
        {
            return Process<CameraController>(source);
        }

        public System.IObservable<string> Process(System.IObservable<CameraControllerTrigger> source)
        {
            return Process<CameraControllerTrigger>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Experiment> source)
        {
            return Process<Experiment>(source);
        }

        public System.IObservable<string> Process(System.IObservable<HarpTimestampGeneratorGen3> source)
        {
            return Process<HarpTimestampGeneratorGen3>(source);
        }

        public System.IObservable<string> Process(System.IObservable<LightCycle> source)
        {
            return Process<LightCycle>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Point> source)
        {
            return Process<Point>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Rig> source)
        {
            return Process<Rig>(source);
        }

        public System.IObservable<string> Process(System.IObservable<Tracking> source)
        {
            return Process<Tracking>(source);
        }

        public System.IObservable<string> Process(System.IObservable<UndergroundFeeder> source)
        {
            return Process<UndergroundFeeder>(source);
        }

        public System.IObservable<string> Process(System.IObservable<WeightScale> source)
        {
            return Process<WeightScale>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.7.1.0 (Newtonsoft.Json v13.0.0.0, YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ActivityCenter>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ActivityTracking>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Camera>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<CameraController>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<CameraControllerTrigger>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Experiment>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HarpTimestampGeneratorGen3>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<LightCycle>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Point>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Rig>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Tracking>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<UndergroundFeeder>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<WeightScale>))]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<ActivityCenter>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}